name: bbseg
env_file:
  - defaults.env
recipe: drupal8
config:
  webroot: www/docroot
  via: apache
  php: '7.3'
  drush: '^8'
  # Uncomment the following to override PHP's configuration.
  # conf:
    # php: config/custom.ini

proxy:
  # Uncomment these lines when the other websites are specified.
  # appserver:
    # - site2.lndo.site
    # - site3.lndo.site
    # - site4.lndo.site
  # edge:
    # - edge.lndo.site

services:
  # appserver:
    # webroot: www/docroot
    # Uncomment the following to enable xdebug + VSCode.
    # xdebug: true
    # config:
      # php: .vscode/php.ini

  database:
    # Using 5.7 as Lando doesn't support Acquia's 5.6.
    type: mysql:5.7

  node:
    type: node:10
    build:
      - /bin/sh -c "if [ ! -z ${LANDO_MOUNT} ]; then cd ${LANDO_MOUNT}/${THEME_PATH} && npm install && npm install gulp -g; fi"
    port: 3054
    # overrides:
      # image: 'agilecollective/lando-node:2.0.2-node8'
      # ports:
        # - '3053:3053' # You should change this port to something random and then update gulpconfig.js in the theme to match

  # cache:
    # type: memcached:1.5.12
    # portforward: true

  # edge:
    # type: varnish
    # ssl: true
    # backends:
      # - appserver

  # mailhog:
    # type: mailhog
    # hogfrom:
      # - appserver
    # portforward: true

tooling:
  # varnishadm:
    # service: edge
    # user: root
  # varnishstat:
    # service: edge
    # user: root
  # varnishlog:
    # service: edge
    # user: root
  theme:
    service: node
    cmd: /app/script.sh
    level: app
    options:
      command:
        passthrough: true
        alias:
          - ni
        describe: Choose the command to run on node container.
        interactive:
          type: input
          default: npm install
  # Drupal Console is not working properly with Acquia Lightning distribution.
  # As a workaround, use this tooling.
  # Docs:
  #   - https://drupalconsole.com/articles/add-drupalconsole-to-a-project-using-acquia-lightning-distribution
  #   - https://github.com/acquia/lightning-project/issues/15#issuecomment-263377964
  dcfix:
    service: appserver
    cmd: composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages --no-update && composer update

